name: SecureCI Pipeline

on:
  push:
  pull_request:

jobs:
  secureci-self-check:
    name: SecureCI Self Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: SecureCI self scan (should always pass)
        run: |
          python secureci.py . config/default_policy.yaml --skip-self

  secureci-scan:
    name: SecureCI Target Scan
    runs-on: ubuntu-latest
    needs: secureci-self-check

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run SecureCI
        run: |
          python secureci.py tests/sample_project --format sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: secureci.sarif
